### ISSUE TITLE
Bug: Text not scaling properly when fullscreened.

### ISSUE THREAD

**Issue by HammerHead133** [TheDrawingCoder-Gamer/FunkinVortex#1]
explains itself
also while you're here can we pretty please get like just a simple help file that lists all the keys used
have no idea whether i cant delete notes due to a bug or if im just not pressing the right key
![image](https://user-images.githubusercontent.com/66718832/121297457-8f10b180-c8af-11eb-99ee-a2de60f29565.png)

**Comment by TheDrawingCoder-Gamer** [comment]
known issue. will be fixed in next commit (thanks to haxeui being updated)
